### PR TITLE
Update dependencies and remove unneeded files

### PR DESCRIPTION
**Pull request by ghost**
add node-key-sender as a dependency
add desktop-screenshot as a dependency
remove unneeded node dependency
remove unneeded mongoose dependency
remove unneeded ffmpeg-static dependency
remove unneeded libsodium-wrappers dependency
remove unused command_exapmle.js file
remove unneeded setup-screenshot.bat file

### CODE REVIEW

**Comment by Awashcard0** [comment]
I will pull it as soon as it lets me

**Comment by Awashcard0** [comment]
We need mongoose

**Comment by ghost** [comment]
Why is mongoose required? Is it for a future update?

**Comment by alaninnovates** [comment]
PR #5 removes the reconlx dependency, therefore removing some peer dependencies such as mongoose.

**Pull request closed without merging**
